name: HTMLKit Tests

on: 
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master

jobs:
  check-doc-coverage:
    runs-on: swift:5.1.3-bionic
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Calculate Documentation Coverage
        uses: MatsMoll/swift-doc@master
        with:
          inputs: "Sources"
          output: "dcov.json"
      - name: Check Documentation Percent
        run: sudo bash CI/check-percentage.sh dcov.json 15
        
  xenial:
    needs: check-doc-coverage
    container: 
      image: swift:5.1.3-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - run: swift test
    
  bionic:
    needs: check-doc-coverage
    container: 
      image: swift:5.1.3-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - run: swift test
    
  release-docs:
    needs: [xenial, bionic]
    runs-on: swift:5.1.3-bionic
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: KognitaModels
          output: "Documentation"
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
