name: HTMLKit Tests

on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - 2.*
      - master

jobs:
  xenial:
    container: 
      image: swift:5.1.3-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - run: swift test
  bionic:
    container: 
      image: swift:5.1.3-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - run: swift test
